version: "3"
services:
  devices-page:
    image: ubports/devices-page
    networks:
      - webgateway
    deploy:
      labels:
        - "traefik.docker.network: webgateway"
        - "traefik.frontend.rule=Host:devices2.ubuntu-touch.io"
        - "traefik.port=2708"

networks:
  webgateway:
    driver: overlay
    external: true
